version: '3.2'

services:

  explorer-api:
    build: explorer-api/.
    image: nftmart/pre-explorer-api:latest
    hostname: explorer-api
    volumes:
      - './explorer-api:/usr/src/app'
    command: ./start.sh
    environment:
      - PYTHONPATH=/usr/src/app
      - ENVIRONMENT=prod
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=polkascan
      - SUBSTRATE_RPC_URL=http://nftmart-node:9933/
      - SUBSTRATE_ADDRESS_TYPE=12191
      - TYPE_REGISTRY=development
    # - TYPE_REGISTRY_FILE=app/type_registry/nftmart_mainnet_types.json
      - SUBSTRATE_METADATA_VERSION=13
      - SUBSTRATE_STORAGE_BALANCE=Account
      - SUBSTRATE_STORAGE_INDICES=Accounts
    depends_on:
      - mysql
      - nftmart-node

  harvester-api:
    build: harvester/.
    image: nftmart/pre-harvester:latest
    hostname: harvester-api
    volumes:
      - './harvester:/usr/src/app'
    command: ./start.sh
    environment: &env
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/usr/src/app:/usr/src/app/py-substrate-interface/:/usr/src/app/py-scale-codec/
      - ENVIRONMENT=prod
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=polkascan
      - SUBSTRATE_RPC_URL=http://nftmart-node:9933/
      - TYPE_REGISTRY=development
      - SUBSTRATE_ADDRESS_TYPE=42
      - SUBSTRATE_METADATA_VERSION=13
      - NEW_SESSION_EVENT_HANDLER=True
      - SUBSTRATE_STORAGE_BALANCE=Account
      - SUBSTRATE_STORAGE_INDICES=Accounts
      - FINALIZATION_ONLY=1

    depends_on:
      - redis
      - mysql
      - nftmart-node

  harvester-worker:
    build: harvester/.
    image: nftmart/pre-harvester:latest
    volumes:
      - './harvester:/usr/src/app'
    command: celery -A app.tasks worker --loglevel=INFO
    environment: *env
    depends_on:
      - redis
      - mysql

  harvester-beat:
    build: harvester/.
    image: nftmart/pre-harvester:latest
    volumes:
      - './harvester:/usr/src/app'
      - '/usr/src/app/data'
    command: celery -A app.tasks beat --loglevel=INFO  --schedule="data/celerybeat-schedule" --pidfile="data/celerybeat.pid"
    environment: *env
    depends_on:
      - redis

  harvester-monitor:
    build: harvester/.
    image: nftmart/pre-harvester:latest
    environment: *env
    ports:
      - '5555:5555'
    command:  flower -A app.tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:3.2.11
    hostname: redis

  mysql:
    image: mysql:8.0.23
    hostname: mysql
    volumes:
      - './db-data:/var/lib/mysql'
    ports:
      - '33061:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=polkascan

  nftmart-node:
    image: nftmart/node:mainnet
    hostname: nftmart-node
    volumes:
      - './nftmart-data:/data'
      - ./mainnetRaw.json/:/mainnetRaw.json
    ports:
      - '30333:30333'
      - '9933:9933'
      - '9944:9944'
    command: --chain=/mainnetRaw.json --base-path=/data --unsafe-ws-external --rpc-cors=all --unsafe-rpc-external --rpc-methods=Unsafe --validator

  explorer-gui:
    image: nftmart/pre-explorer-gui:latest
    build:
      context: explorer-gui/.
      args:
        NETWORK_NAME: NFTMart
        NETWORK_ID: nftmart
        NETWORK_TYPE: pre
        CHAIN_TYPE: relay
        NETWORK_TOKEN_SYMBOL: NMT
        NETWORK_TOKEN_DECIMALS: 12
        NETWORK_COLOR_CODE: f19135
        API_URL: http://127.0.0.1:3000/api/v1
    ports:
      - '3000:80'
    depends_on:
      - harvester-api
      - explorer-api
